### ISSUE TITLE
<BP04> Presionar varias teclas a la vez impide que un jugador pueda reaccionar. <Average>

### ISSUE THREAD

**Issue by Firo77** [Thekhumi/BattlePong#4]
Mientras se juega en cualquier nivel de a dos jugadores, al presionar varias teclas a la vez se puede lograr que un jugador sea incapaz de moverse.

Battlepong v0.10
Windows 10

**Comment by XweetyK** [comment]
En que casos ocurre esto? Todas las teclas al mismo tiempo? Las letras (W/S) cancelan el resto de teclas o viceversa con las flechas (ARRIBA/ABAJO)?
Ocurre en PC de escritorio, Laptop o ambas?

**Comment by Firo77** [comment]
Es un tema de hardware, depende del teclado que uses, algunos te permiten presionar más teclas a la vez que otros. Lo comento para que lo tengan en cuenta pero no estoy seguro que puedan encontrarle una solución.
Con presionar 4 o 5 o más teclas cualquiera el teclado deja de responder y los jugadores pierden el control.
Probado desde pc de escritorio en un teclado Logitech k270.
